
import React from 'react';
import { Button } from "@/components/ui/button";
import { Mail, Printer } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { formatRecommendationForPrint } from "@/utils/markdownRenderer";

interface RecommendationActionsProps {
  recommendation: string;
  onStartNew: () => void;
}

const RecommendationActions: React.FC<RecommendationActionsProps> = ({
  recommendation,
  onStartNew
}) => {
  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
          <head>
            <title>Diet Recommendation</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
              }
              h1 { color: #059669; font-size: 28px; margin-bottom: 20px; }
              h2 { color: #047857; font-size: 24px; margin-top: 30px; margin-bottom: 15px; }
              h3 { color: #065f46; font-size: 20px; margin-top: 25px; margin-bottom: 10px; }
              h4 { color: #064e3b; font-size: 18px; margin-top: 20px; margin-bottom: 8px; }
              h5 { color: #064e3b; font-size: 16px; margin-top: 15px; margin-bottom: 6px; }
              p { margin-bottom: 12px; }
              li { margin-bottom: 6px; margin-left: 20px; }
              .header { text-align: center; margin-bottom: 40px; }
              .footer { text-align: center; margin-top: 40px; color: #666; font-size: 14px; }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>🥗 Your Personalized Diet Recommendation</h1>
              <p style="color: #666;">Generated by NutriAI on ${new Date().toLocaleDateString()}</p>
            </div>
            <div class="content">
              ${formatRecommendationForPrint(recommendation)}
            </div>
            <div class="footer">
              <p>Created with NutriAI - Your AI-Powered Nutrition Assistant</p>
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
      printWindow.close();
    }
    toast.success("Print dialog opened");
  };

  const handleEmail = async () => {
    try {
      toast.info("Preparing to send email...");
      
      const { data, error } = await supabase.functions.invoke('send-recommendation-email', {
        body: { recommendation }
      });

      if (error) {
        throw error;
      }

      toast.success("Recommendation sent to your email!");
    } catch (error) {
      console.error('Error sending email:', error);
      toast.error("Failed to send email. Please try again.");
    }
  };

  return (
    <div className="flex flex-col sm:flex-row gap-4 justify-center">
      <Button onClick={handleEmail} variant="outline" className="flex items-center gap-2">
        <Mail className="w-4 h-4" />
        Email Recommendation
      </Button>
      
      <Button onClick={handlePrint} variant="outline" className="flex items-center gap-2">
        <Printer className="w-4 h-4" />
        Print Recommendation
      </Button>
      
      <Button onClick={onStartNew} variant="outline">
        Start New Assessment
      </Button>
    </div>
  );
};

export default RecommendationActions;
