// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhfhyaymjgahrhozazlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oZmh5YXltamdhaHJob3phemxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzI1NDEsImV4cCI6MjA2NDEwODU0MX0.SmKWp-DGWIncoDqgFZhUT2pZyYSoTc8p3igBhFQvIgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);